# Generated by Django 3.2.12 on 2024-04-24 11:22

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid_currency', djmoney.models.fields.CurrencyField(choices=[('AFN', 'Afghan Afghani'), ('ARS', 'Argentine Peso'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('AZN', 'Azerbaijani Manat'), ('BSD', 'Bahamian Dollar'), ('BDT', 'Bangladeshi Taka'), ('BBD', 'Barbadian Dollar'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudan Dollar'), ('BOB', 'Bolivian Boliviano'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BWP', 'Botswanan Pula'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('BND', 'Brunei Dollar'), ('BGN', 'Bulgarian Lev'), ('KHR', 'Cambodian Riel'), ('CAD', 'Canadian Dollar'), ('KYD', 'Cayman Islands Dollar'), ('CLP', 'Chilean Peso'), ('CNY', 'Chinese Yuan'), ('COP', 'Colombian Peso'), ('CRC', 'Costa Rican Colón'), ('HRK', 'Croatian Kuna'), ('CUP', 'Cuban Peso'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('DOP', 'Dominican Peso'), ('XCD', 'East Caribbean Dollar'), ('EGP', 'Egyptian Pound'), ('EEK', 'Estonian Kroon'), ('EUR', 'Euro'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fijian Dollar'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GIP', 'Gibraltar Pound'), ('GTQ', 'Guatemalan Quetzal'), ('GYD', 'Guyanaese Dollar'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IMP', 'IMP'), ('ISK', 'Icelandic Króna'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('IRR', 'Iranian Rial'), ('ILS', 'Israeli New Shekel'), ('JMD', 'Jamaican Dollar'), ('JPY', 'Japanese Yen'), ('KZT', 'Kazakhstani Tenge'), ('KWD', 'Kuwaiti Dinar'), ('KGS', 'Kyrgystani Som'), ('LAK', 'Laotian Kip'), ('LVL', 'Latvian Lats'), ('LBP', 'Lebanese Pound'), ('LRD', 'Liberian Dollar'), ('LTL', 'Lithuanian Litas'), ('MKD', 'Macedonian Denar'), ('MYR', 'Malaysian Ringgit'), ('MUR', 'Mauritian Rupee'), ('MXN', 'Mexican Peso'), ('MNT', 'Mongolian Tugrik'), ('MZN', 'Mozambican Metical'), ('NAD', 'Namibian Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NGN', 'Nigerian Naira'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('OMR', 'Omani Rial'), ('PKR', 'Pakistani Rupee'), ('PAB', 'Panamanian Balboa'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('PHP', 'Philippine Peso'), ('PLN', 'Polish Zloty'), ('QAR', 'Qatari Riyal'), ('RON', 'Romanian Leu'), ('RUB', 'Russian Ruble'), ('SVC', 'Salvadoran Colón'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('SCR', 'Seychellois Rupee'), ('SGD', 'Singapore Dollar'), ('SBD', 'Solomon Islands Dollar'), ('SOS', 'Somali Shilling'), ('ZAR', 'South African Rand'), ('KRW', 'South Korean Won'), ('LKR', 'Sri Lankan Rupee'), ('SHP', 'St. Helena Pound'), ('SRD', 'Surinamese Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('TVD', 'TVD'), ('THB', 'Thai Baht'), ('TTD', 'Trinidad & Tobago Dollar'), ('TRY', 'Turkish Lira'), ('TRL', 'Turkish Lira (1922–2005)'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia'), ('AED', 'United Arab Emirates Dirham'), ('UYU', 'Uruguayan Peso'), ('UZS', 'Uzbekistani Som'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VND', 'Vietnamese Dong'), ('XOF', 'West African CFA Franc'), ('YER', 'Yemeni Rial'), ('ZWD', 'Zimbabwean Dollar (1980–2008)')], default='PLN', editable=False, max_length=3)),
                ('amount_paid', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='PLN', editable=False, max_digits=14, null=True)),
                ('paid', models.BooleanField(default=False, editable=False)),
                ('fufiled', models.BooleanField(default=False, editable=False)),
                ('buyer_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('stripe_checkout_id', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentaccount')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.userstore')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', editable=False, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0, editable=False)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('AFN', 'Afghan Afghani'), ('ARS', 'Argentine Peso'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('AZN', 'Azerbaijani Manat'), ('BSD', 'Bahamian Dollar'), ('BDT', 'Bangladeshi Taka'), ('BBD', 'Barbadian Dollar'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudan Dollar'), ('BOB', 'Bolivian Boliviano'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BWP', 'Botswanan Pula'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('BND', 'Brunei Dollar'), ('BGN', 'Bulgarian Lev'), ('KHR', 'Cambodian Riel'), ('CAD', 'Canadian Dollar'), ('KYD', 'Cayman Islands Dollar'), ('CLP', 'Chilean Peso'), ('CNY', 'Chinese Yuan'), ('COP', 'Colombian Peso'), ('CRC', 'Costa Rican Colón'), ('HRK', 'Croatian Kuna'), ('CUP', 'Cuban Peso'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('DOP', 'Dominican Peso'), ('XCD', 'East Caribbean Dollar'), ('EGP', 'Egyptian Pound'), ('EEK', 'Estonian Kroon'), ('EUR', 'Euro'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fijian Dollar'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GIP', 'Gibraltar Pound'), ('GTQ', 'Guatemalan Quetzal'), ('GYD', 'Guyanaese Dollar'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IMP', 'IMP'), ('ISK', 'Icelandic Króna'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('IRR', 'Iranian Rial'), ('ILS', 'Israeli New Shekel'), ('JMD', 'Jamaican Dollar'), ('JPY', 'Japanese Yen'), ('KZT', 'Kazakhstani Tenge'), ('KWD', 'Kuwaiti Dinar'), ('KGS', 'Kyrgystani Som'), ('LAK', 'Laotian Kip'), ('LVL', 'Latvian Lats'), ('LBP', 'Lebanese Pound'), ('LRD', 'Liberian Dollar'), ('LTL', 'Lithuanian Litas'), ('MKD', 'Macedonian Denar'), ('MYR', 'Malaysian Ringgit'), ('MUR', 'Mauritian Rupee'), ('MXN', 'Mexican Peso'), ('MNT', 'Mongolian Tugrik'), ('MZN', 'Mozambican Metical'), ('NAD', 'Namibian Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NGN', 'Nigerian Naira'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('OMR', 'Omani Rial'), ('PKR', 'Pakistani Rupee'), ('PAB', 'Panamanian Balboa'), ('PYG', 'Paraguayan Guarani'), ('PEN', 'Peruvian Sol'), ('PHP', 'Philippine Peso'), ('PLN', 'Polish Zloty'), ('QAR', 'Qatari Riyal'), ('RON', 'Romanian Leu'), ('RUB', 'Russian Ruble'), ('SVC', 'Salvadoran Colón'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('SCR', 'Seychellois Rupee'), ('SGD', 'Singapore Dollar'), ('SBD', 'Solomon Islands Dollar'), ('SOS', 'Somali Shilling'), ('ZAR', 'South African Rand'), ('KRW', 'South Korean Won'), ('LKR', 'Sri Lankan Rupee'), ('SHP', 'St. Helena Pound'), ('SRD', 'Surinamese Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('TVD', 'TVD'), ('THB', 'Thai Baht'), ('TTD', 'Trinidad & Tobago Dollar'), ('TRY', 'Turkish Lira'), ('TRL', 'Turkish Lira (1922–2005)'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia'), ('AED', 'United Arab Emirates Dirham'), ('UYU', 'Uruguayan Peso'), ('UZS', 'Uzbekistani Som'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VND', 'Vietnamese Dong'), ('XOF', 'West African CFA Franc'), ('YER', 'Yemeni Rial'), ('ZWD', 'Zimbabwean Dollar (1980–2008)')], default='PLN', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='PLN', editable=False, max_digits=14, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.userstoreproduct')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.transaction')),
            ],
        ),
    ]
