# Generated by Django 3.2.12 on 2024-04-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240429_2106'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransactionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('store_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_transaction_stats', to='store.storeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_store_transactions', to='payments.dailytransactionstat'),
        ),
    ]
