# Generated by Django 3.2.12 on 2024-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20240429_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=1000),
        ),
    ]
