# Generated by Django 3.2.12 on 2024-05-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='session_id',
        ),
    ]
