# Generated by Django 3.2.12 on 2024-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
    ]
