# Generated by Django 3.2.12 on 2024-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20240519_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransactionstat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
