# Generated by Django 3.2.12 on 2024-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_dailytransactionstat_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_ordered',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
