# Generated by Django 3.2.12 on 2024-06-08 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction_amount_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytransactionstat',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='dailytransactionstat',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
